# Generated by Django 5.0.14 on 2025-10-30 11:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.IntegerField(default=100, help_text='ユーザーが1ヶ月に生成できる画像の最大枚数', validators=[django.core.validators.MinValueValidator(0)], verbose_name='月間利用可能回数')),
                ('monthly_used', models.IntegerField(default=0, help_text='当月に既に生成した画像の枚数', validators=[django.core.validators.MinValueValidator(0)], verbose_name='当月利用済み回数')),
                ('is_deleted', models.BooleanField(default=False, help_text='論理削除フラグ', verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザープロファイル',
                'verbose_name_plural': 'ユーザープロファイル',
                'db_table': 'user_profile',
                'db_table_comment': 'ユーザープロファイル拡張テーブル',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_deleted', 'created_at'], name='user_profil_is_dele_795573_idx')],
            },
        ),
    ]
