# Generated by Django 5.0.14 on 2025-11-01 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='user_profil_is_dele_795573_idx',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_deleted',
        ),
    ]
