# Generated by Django 5.0.14 on 2025-10-30 11:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image_path', models.CharField(max_length=500, verbose_name='元画像パス')),
                ('original_image_name', models.CharField(max_length=255, verbose_name='元画像ファイル名')),
                ('original_image_size', models.IntegerField(verbose_name='元画像サイズ（バイト）')),
                ('prompt', models.TextField(help_text='画像変換に使用したプロンプト', verbose_name='使用プロンプト')),
                ('generation_count', models.IntegerField(help_text='生成する画像の枚数（1-5枚）', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='生成枚数')),
                ('status', models.CharField(choices=[('pending', '処理待ち'), ('processing', '処理中'), ('completed', '完了'), ('failed', '失敗'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='処理ステータス')),
                ('processing_time', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='処理時間（秒）')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='エラーメッセージ')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '画像変換履歴',
                'verbose_name_plural': '画像変換履歴',
                'db_table': 'image_conversion',
                'db_table_comment': '画像変換履歴テーブル',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=500, verbose_name='画像パス')),
                ('image_name', models.CharField(max_length=255, verbose_name='画像ファイル名')),
                ('image_size', models.IntegerField(verbose_name='画像サイズ（バイト）')),
                ('brightness_adjustment', models.IntegerField(default=0, help_text='輝度調整値（-50〜+50）', validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)], verbose_name='輝度調整値')),
                ('expires_at', models.DateTimeField(help_text='生成日から30日後に自動削除', verbose_name='削除予定日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='images.imageconversion', verbose_name='変換履歴')),
            ],
            options={
                'verbose_name': '生成画像',
                'verbose_name_plural': '生成画像',
                'db_table': 'generated_image',
                'db_table_comment': '生成画像テーブル',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='プリセットの表示名', max_length=100, verbose_name='プリセット名')),
                ('prompt', models.TextField(help_text='実際にAPIに送信するプロンプト文', verbose_name='プロンプト')),
                ('category', models.CharField(choices=[('style', 'スタイル'), ('background', '背景'), ('enhancement', '強調'), ('tone', 'トーン'), ('professional', 'プロフェッショナル'), ('other', 'その他')], default='other', max_length=20, verbose_name='カテゴリ')),
                ('description', models.TextField(blank=True, help_text='プリセットの詳細説明', verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, help_text='無効にするとUIに表示されなくなる', verbose_name='有効フラグ')),
                ('display_order', models.IntegerField(default=0, help_text='小さい数字ほど前に表示される', verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'プロンプトプリセット',
                'verbose_name_plural': 'プロンプトプリセット',
                'db_table': 'prompt_preset',
                'db_table_comment': 'プロンプトプリセットテーブル',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='prompt_pres_is_acti_1c8eb0_idx'), models.Index(fields=['category', 'is_active'], name='prompt_pres_categor_a42f38_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='imageconversion',
            index=models.Index(fields=['user', '-created_at'], name='image_conve_user_id_7c4c89_idx'),
        ),
        migrations.AddIndex(
            model_name='imageconversion',
            index=models.Index(fields=['status', 'created_at'], name='image_conve_status_1ab6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='imageconversion',
            index=models.Index(fields=['is_deleted', '-created_at'], name='image_conve_is_dele_c91027_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedimage',
            index=models.Index(fields=['conversion', 'created_at'], name='generated_i_convers_760e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedimage',
            index=models.Index(fields=['expires_at', 'is_deleted'], name='generated_i_expires_cb7432_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedimage',
            index=models.Index(fields=['is_deleted', '-created_at'], name='generated_i_is_dele_780bb0_idx'),
        ),
    ]
