# Generated by Django 5.0.14 on 2025-11-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageconversion',
            name='aspect_ratio',
            field=models.CharField(choices=[('1:1', '1:1'), ('3:4', '3:4'), ('4:3', '4:3'), ('9:16', '9:16'), ('16:9', '16:9'), ('3:2', '3:2'), ('2:3', '2:3'), ('21:9', '21:9'), ('9:21', '9:21'), ('4:5', '4:5')], default='4:3', help_text='生成する画像のアスペクト比', max_length=10, verbose_name='画像比率'),
        ),
    ]
