# Generated by Django 5.0.14 on 2025-11-05 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_imageconversion_aspect_ratio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoritePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='images.promptpreset', verbose_name='プリセット')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_prompts', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'お気に入りプロンプト',
                'verbose_name_plural': 'お気に入りプロンプト',
                'db_table': 'user_favorite_prompt',
                'db_table_comment': 'ユーザーお気に入りプロンプトテーブル',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_favori_user_id_0bafc5_idx')],
                'unique_together': {('user', 'preset')},
            },
        ),
    ]
